### ISSUE TITLE
Support for IAM Role permission boundary

### ISSUE THREAD

**Issue by jonesg504** [howdio/terraform-aws-eks#18]
I need to add permission boundaries to any roles I create.

**Comment by eana** [comment]
I am already working on this and I will open a PR in the next coming days.

**Comment by eana** [comment]
@jonesg504 sorry for the delay, I got swamped with work. Here is the PR, please test it out. I tested it myself, but it would be good if could add a comment on the PR to confirm that everything is working fine.

https://github.com/howdio/terraform-aws-eks/pull/23

Thanks

**Comment by eana** [comment]
@jonesg504 the PR was merged to master.
