### ISSUE TITLE
Assistance 

### ISSUE THREAD

**Issue by ayotec2015** [howdio/terraform-aws-eks#20]
HI, 

I am new to this. I have to questions. 

1) The kubectl seems up all deployments are fine but the nodes are not up. Am I missing something ? 

2) How do I ssh into the nodes. added in a ssh module to generate ssh key and opened the ports but still doesn't connect in.

**Comment by ayotec2015** [comment]
Actually I think its the VPC that is restricting access to the nodes. What would be the easiest way to get into the nodes.

**Comment by eana** [comment]
Unfortunately, the details you're giving here are not enough to troubleshoot your problem.
To enable `ssh` access to your nodes you will need to define `ssh_cidr` and `key_pair`.

**Comment by ayotec2015** [comment]
Sorry  I wasn't clear, I have enabled the ssh keypair and also opened the port 22. But I am still not able to ssh into the nodes. I have also enabled public DNS and public IP but still not able to ssh to the nodes. Am not sure if I am missing something else in the VPC to allow connections to the nodes. 

Thanks

**Comment by eana** [comment]
So can you confirm that you have defined the `ssh_cidr` to whatever ip address or ip range you're on? Assuming your ip address is `86.106.192.92`

```
variable "ssh_cidr" {
  default     = "86.106.192.92/32"
  description = "The CIDR blocks from which to allow incoming ssh connections to the EKS nodes."
}
```

**Comment by ayotec2015** [comment]
HI I have 
variable "ssh_cidr" {
  default     = "0.0.0.0/0"
  description = "The CIDR blocks from which to allow incoming ssh connections to the EKS nodes."
}

I have the full block open so I can give a test but still doesn't seem to work.

**Comment by eana** [comment]
To which IP are you trying to connect to, `public` or `private`? You should try to connect to the `public` one.

**Comment by ayotec2015** [comment]
HI,, Managed to resolve it. 

Thanks for your help
